name: ajk-lomake
version: 0.1.0.0
synopsis: AJK form 
description: Jee jee 
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: osakunta/ajk-lomake
category: Web
tested-with: GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.9
    - aeson                 >=0.8   && <0.11
    - aeson-compat
    - base-compat
    - bifunctors
    - blaze-html
    - bytestring
    - containers
    - either
    - file-embed
    - generics-sop
    - http-client
    - http-client-tls
    - lens
    - lucid
    - markdown
    - mtl
    - pretty
    - semigroups
    - servant
    - servant-lucid
    - servant-server
    - stm
    - tagged
    - text
    - time
    - transformers
    - unordered-containers
    - vector
    - wai
    - warp

executables:
  ajk-lomake-server:
    ghc-options: -threaded
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - ajk-lomake
      - hdaemonize
