resolver: nightly-2017-04-01
packages:
- '.'
- location:
    git: https://github.com/futurice/haskell-futurice-prelude.git
    commit: 8a613952a500021aed6c98ed9588f34c38285876
  extra-dep: true
extra-deps:
- ansi-pretty-0.1.2.1
flags: {}
extra-package-dbs: []
